### ISSUE TITLE
Error In just the printing statement

### ISSUE THREAD

**Issue by inst-cicada** [nseadlc-2020/package-todo-cli-task#12]
**Expected: StringContaining "[3] find needle in the haystack
    [2] water the plants
    [1] the thing i need to do
    "
    Received: "[3] find needle in the haystack·
    [2] water the plants·
    [1] the thing i need to do·**
    "

I tried to put **\n**, **different print()**, and also tried **tripple quoted strings** but I dont know from where that **(·)dot** comes when I test the code with **npm test**. While testing with my powershell everything is fine with no dots but with npm test there is dots. Please help.

Name: Abhishek Joshi

**Comment by harigopal** [comment]
@inst-cicada Could you check for trailing spaces in your output? It's likely that the _dot_ character is being used to indicate additional spaces at the end of the line in your output.

The test doesn't handle additional spaces _within_ the output lines, at the moment.

**Comment by rishabh-karmakar** [comment]
The same error persists in my system too. I'm using python and regardless of whatever is done, regex, strip, split, join; nothing works. Removing whitespace, newlines, others, nothing is working.
What is to be done?

**Comment by MrAdiii** [comment]
I'm having the same issue, **where that (·)dot comes when I test the code with npm test** with **_Python_**

I'm not a specialist but I think its becz windows uses **Windows-1252** and npm tests are converting text to **utf-8**. on Top of that (**again i think**) python by default uses system encoder "Windows-1252" on Windows and after python 2.0 there is no easy option to change encoding (or I'm unable to find) **so that "\n" (Windows-1252) is converted to (·) utf-8** still not sure

- and python3 should be replaced with python in todo.bat to make it run on Windows other wise it gives "Python Not Found!"

 **I tried my code on Ubuntu (linux) and it works without any problem 👍** 

**EDIT:**
**found a solution** for Python on Windows

instead of print(string_variable) try **sys.stdout.buffer.write(string_variable.encode('utf8'))** and don't forget to **import sys** to print to console, _(where String_variable is ur variable name)_

Hope helps :-)

**Comment by rishabh-karmakar** [comment]
Yeah, I'll try doing that. Thanks a lot @MrAdiii!

**Comment by penanrajput** [comment]
I am using Cpp,  can you tell me the solution for dot problem ???

**Comment by MrAdiii** [comment]
> I am using Cpp,  can you tell me the solution for dot problem ???

Try on Linux, running on Ubuntu fix the problem for me in Python

**Comment by rishabh-karmakar** [comment]
> I am using Cpp, can you tell me the solution for dot problem ???

Yeah @MrAdiii is right, try linux. If you dont have a linux operating sys, try using one with the help of VMWare.

One more workaround discovered was that in python using the print statement with end in no spaces as print(text,end='') also works. Since python by default has end='\n', changing it to '' would help.

**Comment by sauravUppoor** [comment]
> > I am using Cpp, can you tell me the solution for dot problem ???
> 
> Yeah @MrAdiii is right, try linux. If you dont have a linux operating sys, try using one with the help of VMWare.
> 
> One more workaround discovered was that in python using the print statement with end in no spaces as print(text,end='') also works. Since python by default has end='\n', changing it to '' would help.

The python workaround didn't work for me in Windows. 
Instead for python, I used `sys.stdout.buffer.write(string_variable.encode('utf8'))` where `string_variable` is your string you want to display.

**Comment by MrAdiii** [comment]
found a solution for Python on Windows

instead of print(string_variable) try **sys.stdout.buffer.write(string_variable.encode('utf8'))** and don't forget to **import sys** to print to console, _(where String_variable is ur variable name)_

thanks to 
Saurav Uppoor

**Comment by penanrajput** [comment]
todo app took 4-5 hours to code in **C++** on **Windows 10** 😊, but "\n" is converted to dot(·)
its been 1 day, but couldn't find the solution...... 
I tried every possible way to encode but couldn't find the solution, and I don't have Linux to test code ☹
Here's the screenshot 📸 : **npm test**
![2020-12-18_10_55_57_Code](https://user-images.githubusercontent.com/40760103/102579497-90dc9200-4122-11eb-86a7-fd82619cbeb4.jpg)

What's solution of this issue ??

**Comment by inst-cicada** [comment]
> @inst-cicada Could you check for trailing spaces in your output? It's likely that the _dot_ character is being used to indicate additional spaces at the end of the line in your output.
> 
> The test doesn't handle additional spaces _within_ the output lines, at the moment.

**Comment by inst-cicada** [comment]
> @inst-cicada Could you check for trailing spaces in your output? It's likely that the _dot_ character is being used to indicate additional spaces at the end of the line in your output.
> 
> The test doesn't handle additional spaces _within_ the output lines, at the moment.

I fixed the issue. It took because I was having exams. I encoded it to utf8. It fixed it for me. Thank you.

**Comment by inst-cicada** [comment]
> todo app took 4-5 hours to code in **C++** on **Windows 10** 😊, but "\n" is converted to dot(·)
> its been 1 day, but couldn't find the solution......
> I tried every possible way to encode but couldn't find the solution, and I don't have Linux to test code ☹
> Here's the screenshot 📸 : **npm test**
> ![2020-12-18_10_55_57_Code](https://user-images.githubusercontent.com/40760103/102579497-90dc9200-4122-11eb-86a7-fd82619cbeb4.jpg)
> 
> What's solution of this issue ??

Solution is to encode the output to 'utf8'. Im not sure for c++ but in python it fixed the issue.

**Comment by inst-cicada** [comment]
> found a solution for Python on Windows
> 
> instead of print(string_variable) try **sys.stdout.buffer.write(string_variable.encode('utf8'))** and don't forget to **import sys** to print to console, _(where String_variable is ur variable name)_
> 
> thanks to
> Saurav Uppoor

Yes. Sempai. ;-)

**Comment by MrAdiii** [comment]
> todo app took 4-5 hours to code in **C++** on **Windows 10** 😊, but "\n" is converted to dot(·)
> its been 1 day, but couldn't find the solution...... 
> I tried every possible way to encode but couldn't find the solution, and I don't have Linux to test code ☹
> Here's the screenshot 📸 : **npm test**
> ![2020-12-18_10_55_57_Code](https://user-images.githubusercontent.com/40760103/102579497-90dc9200-4122-11eb-86a7-fd82619cbeb4.jpg)
> 
> What's solution of this issue ??

https://stackoverflow.com/questions/45575863/how-to-print-utf-8-strings-to-stdcout-on-windows

I haven't tried but, check this

**Comment by anshulsinghchouhan4** [comment]
I am facing issues with npm test, Can anyone help me out ?
![image](https://user-images.githubusercontent.com/42866522/102697175-dcde2280-4259-11eb-896b-feb4732b1924.png)

**Comment by anshulsinghchouhan4** [comment]
**I am facing issues with NPM test, Can any help me out ?**
I dont know what is meaning of this error :(

![image](https://user-images.githubusercontent.com/42866522/102697272-a81e9b00-425a-11eb-9a3d-c46de32b7f8b.png)

**Comment by inst-cicada** [comment]
> **I am facing issues with NPM test, Can any help me out ?**
> I dont know what is meaning of this error :(
> 
> ![image](https://user-images.githubusercontent.com/42866522/102697272-a81e9b00-425a-11eb-9a3d-c46de32b7f8b.png)

Please try to run npm test from the directory where your todo.py and todo.bat files are. Running it in default path won't help you!

**Comment by anshulsinghchouhan4** [comment]
Now its showing this ? 
Can you tell me, what can I do now ?

![image](https://user-images.githubusercontent.com/42866522/102698095-dbfcbf00-4260-11eb-8105-40d2d4fcc318.png)

**Comment by inst-cicada** [comment]
> Now its showing this ?
> Can you tell me, what can I do now ?
> 
> ![image](https://user-images.githubusercontent.com/42866522/102698095-dbfcbf00-4260-11eb-8105-40d2d4fcc318.png)

Before running npm test in yout todo directory please install jest by `**npm install -g jest**` and then run `**npm test**`
Good luck @anshulsinghchouhan4

**Comment by inst-cicada** [comment]
> Now its showing this ?
> Can you tell me, what can I do now ?
> 
> ![image](https://user-images.githubusercontent.com/42866522/102698095-dbfcbf00-4260-11eb-8105-40d2d4fcc318.png)

Before running npm test in your todo.py directory please run `npm install -g jest` command to install jest and after that you can use `npm test` . Good Luck @anshulsinghchouhan4

**Comment by MadHawkx** [comment]
Hello, 
npm test is throwing this error

'D:\Java' is not recognized as an internal or external command,
operable program or batch file.

Everything is working fine on command line, it is npm test which is showing errors

**Comment by divyammadhok** [comment]
Hello,
npm test is throwing this error

'D:\Java' is not recognized as an internal or external command,
operable program or batch file.

Everything is working fine on command line, it is npm test which is showing errors. My working folder is in "D:\java"

**Comment by Neelam-Nishad** [comment]
![Screenshot (38)](https://user-images.githubusercontent.com/73290803/102700841-f5106a80-4276-11eb-8474-6cd235c08272.png)

Help me please!!
having problem to run todo 
it runs fine when I manually type ./todo
but when it was manually opend by test this error occurs " C:\Users\Neelam\OneDrive\Desktop\project\java/todo"
How to fix this??

**Comment by Neelam-Nishad** [comment]
![Screenshot (39)](https://user-images.githubusercontent.com/73290803/102700908-98fa1600-4277-11eb-878b-974ff2be408d.png)
Here it works fine when I manually type ./todo

**Comment by udaygajavalli** [comment]
> ![Screenshot (38)](https://user-images.githubusercontent.com/73290803/102700841-f5106a80-4276-11eb-8474-6cd235c08272.png)
> 
> Help me please!!
> having problem to run todo
> it runs fine when I manually type ./todo
> but when it was manually opend by test this error occurs " C:\Users\Neelam\OneDrive\Desktop\project\java/todo"
> How to fix this??

The issue was with your directory path which contains space in the folder names and child_process package couldn't able to resolve it.
This problem occurred due to the test cases which didn't handled this error.

**Comment by udaygajavalli** [comment]
> Hello,
> npm test is throwing this error
> 
> 'D:\Java' is not recognized as an internal or external command,
> operable program or batch file.
> 
> Everything is working fine on command line, it is npm test which is showing errors. My working folder is in "D:\java"

The issue was might be  with your directory path which contains space in the folder names and child_process package couldn't able to resolve it in todo.test.js.

**Comment by Neelam-Nishad** [comment]
> > Hello,
> > npm test is throwing this error
> > 'D:\Java' is not recognized as an internal or external command,
> > operable program or batch file.
> > Everything is working fine on command line, it is npm test which is showing errors. My working folder is in "D:\java"
> 
> The issue was might be with your directory path which contains space in the folder names and child_process package couldn't able to resolve it in todo.test.js.


export is not for windows maybe , how to change that , because of export command this line is reoccuring 
'export' is not recognized as an internal or external command,

**Comment by sauravUppoor** [comment]
> 
> Help me please!!
> having problem to run todo
> it runs fine when I manually type ./todo
> but when it was manually opend by test this error occurs " C:\Users\Neelam\OneDrive\Desktop\project\java/todo"
> How to fix this??

As others said, its due to space in the path name. So here's how you can fix it (it worked for me):
In the todo.test.js, replace the line **let todoTxtCli = (...args) => [\`${__dirname}/todo\`, ...args].join(" ");** with this **let todoTxtCli = (...args) => [\`"${__dirname}"\\todo`, ...args].join(" ");** 

This will tell the cmd that the space encountered is a part of the path and it wont end there. Hope this helps.

**Comment by udaygajavalli** [comment]
> > Help me please!!
> > having problem to run todo
> > it runs fine when I manually type ./todo
> > but when it was manually opend by test this error occurs " C:\Users\Neelam\OneDrive\Desktop\project\java/todo"
> > How to fix this??
> 
> As others said, its due to space in the path name. So here's how you can fix it (it worked for me):
> In the todo.test.js, replace the line **let todoTxtCli = (...args) => [`${__dirname}/todo`, ...args].join(" ");** with this **let todoTxtCli = (...args) => [`"${__dirname}"\todo`, ...args].join(" ");**
> 
> This will tell the cmd that the space encountered is a part of the path and it wont end there. Hope this helps.

It works in some cases but didn't work for me.

**Comment by anshulsinghchouhan4** [comment]
**WHEN I TRY TO RUN IT, IT'S TAKE A LOT OF TIME** 
Can anyone tell how much time it takes ? 

![image](https://user-images.githubusercontent.com/42866522/102709285-22890280-42cf-11eb-9c6e-9a87b53d9d6a.png)

**Comment by udaygajavalli** [comment]
> **WHEN I TRY TO RUN IT, IT'S TAKE A LOT OF TIME**
> Can anyone tell how much time it takes ?
> 
> ![image](https://user-images.githubusercontent.com/42866522/102709285-22890280-42cf-11eb-9c6e-9a87b53d9d6a.png)

For me, it took around 10 to 20 seconds.

**Comment by farhaanxxiv** [comment]
Please help me with this someone. I am new to programming in Java. Stuck on this for more than 1 day. 

![Screenshot 2020-12-20 142445](https://user-images.githubusercontent.com/70432375/102709297-3b91b380-42cf-11eb-9d6c-9ab155784aa5.png)

**Comment by anshulsinghchouhan4** [comment]
> > **WHEN I TRY TO RUN IT, IT'S TAKE A LOT OF TIME**
> > Can anyone tell how much time it takes ?
> > ![image](https://user-images.githubusercontent.com/42866522/102709285-22890280-42cf-11eb-9c6e-9a87b53d9d6a.png)
> 
> For me, it took around 10 to 20 seconds.

I wait for more than 5 minute still, it didn't run the file. Can you tell me what can I do

**Comment by udaygajavalli** [comment]
> > > **WHEN I TRY TO RUN IT, IT'S TAKE A LOT OF TIME**
> > > Can anyone tell how much time it takes ?
> > > ![image](https://user-images.githubusercontent.com/42866522/102709285-22890280-42cf-11eb-9c6e-9a87b53d9d6a.png)
> > 
> > 
> > For me, it took around 10 to 20 seconds.
> 
> I wait for more than 5 minute still, it didn't run the file. Can you tell me what can I do

Did you run the command `npm install` before executing the `npm test` command?

**Comment by anshulsinghchouhan4** [comment]
> > > > **WHEN I TRY TO RUN IT, IT'S TAKE A LOT OF TIME**
> > > > Can anyone tell how much time it takes ?
> > > > ![image](https://user-images.githubusercontent.com/42866522/102709285-22890280-42cf-11eb-9c6e-9a87b53d9d6a.png)
> > > 
> > > 
> > > For me, it took around 10 to 20 seconds.
> > 
> > 
> > I wait for more than 5 minute still, it didn't run the file. Can you tell me what can I do
> 
> Did you run the command `npm install` before executing the `npm test` command?

YES

**Comment by farhaanxxiv** [comment]
> > > **WHEN I TRY TO RUN IT, IT'S TAKE A LOT OF TIME**
> > > Can anyone tell how much time it takes ?
> > > ![image](https://user-images.githubusercontent.com/42866522/102709285-22890280-42cf-11eb-9c6e-9a87b53d9d6a.png)
> > 
> > 
> > For me, it took around 10 to 20 seconds.
> 
> I wait for more than 5 minute still, it didn't run the file. Can you tell me what can I do

How did you run your first test?

**Comment by anshulsinghchouhan4** [comment]
> > > > **WHEN I TRY TO RUN IT, IT'S TAKE A LOT OF TIME**
> > > > Can anyone tell how much time it takes ?
> > > > ![image](https://user-images.githubusercontent.com/42866522/102709285-22890280-42cf-11eb-9c6e-9a87b53d9d6a.png)
> > > 
> > > 
> > > For me, it took around 10 to 20 seconds.
> > 
> > 
> > I wait for more than 5 minute still, it didn't run the file. Can you tell me what can I do
> 
> How did you run your first test?

What do you mean ?

**Comment by Neelam-Nishad** [comment]
![Screenshot (44)](https://user-images.githubusercontent.com/73290803/102709940-cb862c00-42d4-11eb-9cde-2f961f15a723.png)

export is not recognized as internal or external command,
How to fix this??

**Comment by Neelam-Nishad** [comment]
I am working in windows , and why this problem is occurring.
export is not recognized as internal or external command

**Comment by anshulsinghchouhan4** [comment]
> ![Screenshot (44)](https://user-images.githubusercontent.com/73290803/102709940-cb862c00-42d4-11eb-9cde-2f961f15a723.png)
> 
> export is not recognized as internal or external command,
> How to fix this??

That time my file is in a folder whose name having space, So I change the path and error resolve.

**Comment by Neelam-Nishad** [comment]
> > ![Screenshot (44)](https://user-images.githubusercontent.com/73290803/102709940-cb862c00-42d4-11eb-9cde-2f961f15a723.png)
> > export is not recognized as internal or external command,
> > How to fix this??
> 
> That time my file is in an folder whose name having space, So I change the path and error resolve.

My file path doesn't have space now.. I removed that .

**Comment by anshulsinghchouhan4** [comment]
> > > ![Screenshot (44)](https://user-images.githubusercontent.com/73290803/102709940-cb862c00-42d4-11eb-9cde-2f961f15a723.png)
> > > export is not recognized as internal or external command,
> > > How to fix this??
> > 
> > 
> > That time my file is in an folder whose name having space, So I change the path and error resolve.
> 
> My file path doesn't have space now.. I removed that .

Ping me on linkedIn https://www.linkedin.com/in/anshulsinghchouhan4/

**Comment by Neelam-Nishad** [comment]
> ![Screenshot (44)](https://user-images.githubusercontent.com/73290803/102709940-cb862c00-42d4-11eb-9cde-2f961f15a723.png)
> 
> export is not recognized as internal or external command,
> How to fix this??

I even changed the path of the file .. but still the same problem is arising. 
export command is not recognized .

**Comment by udaygajavalli** [comment]
> > ![Screenshot (44)](https://user-images.githubusercontent.com/73290803/102709940-cb862c00-42d4-11eb-9cde-2f961f15a723.png)
> > export is not recognized as internal or external command,
> > How to fix this??
> 
> I even changed the path of the file .. but still the same problem is arising.
> export command is not recognized .

Try this fix : https://stackoverflow.com/questions/55443351/how-to-solve-vscode-unsupportedclassversionerror

**Comment by anurajbhandari5** [comment]
we have to write a code for what i can not understand ...can anyone tell me what we have to do in this challenge ,..
can we write some code or using only CLI or any other thing??

**Comment by dushivani** [comment]
> ![Screenshot (38)](https://user-images.githubusercontent.com/73290803/102700841-f5106a80-4276-11eb-8474-6cd235c08272.png)
> 
> Help me please!!
> having problem to run todo
> it runs fine when I manually type ./todo
> but when it was manually opend by test this error occurs " C:\Users\Neelam\OneDrive\Desktop\project\java/todo"
> How to fix this??

Did you find any solution ?? I am also facing this issue...

**Comment by udaygajavalli** [comment]
> > ![Screenshot (38)](https://user-images.githubusercontent.com/73290803/102700841-f5106a80-4276-11eb-8474-6cd235c08272.png)
> > Help me please!!
> > having problem to run todo
> > it runs fine when I manually type ./todo
> > but when it was manually opend by test this error occurs " C:\Users\Neelam\OneDrive\Desktop\project\java/todo"
> > How to fix this??
> 
> Did you find any solution ?? I am also facing this issue...

Maybe this could help you https://github.com/nseadlc-2020/package-todo-cli-task/pull/34
btw, Please let me know if it had worked in your case!

**Comment by divyammadhok** [comment]
![image](https://user-images.githubusercontent.com/40322760/102711963-96350a80-42e3-11eb-8472-a7859bbf1924.png)

Hi why is it throwing error? I am not printing full stops but they are automatically being appended
IN java

**Comment by dushivani** [comment]
> > @inst-cicada Could you check for trailing spaces in your output? It's likely that the _dot_ character is being used to indicate additional spaces at the end of the line in your output.
> > The test doesn't handle additional spaces _within_ the output lines, at the moment.
> 
> I fixed the issue. It took because I was having exams. I encoded it to utf8. It fixed it for me. Thank you.

Can you please tell how to solve this issue for c++ on windows?

**Comment by Neelam-Nishad** [comment]
> > todo app took 4-5 hours to code in **C++** on **Windows 10** 😊, but "\n" is converted to dot(·)
> > its been 1 day, but couldn't find the solution......
> > I tried every possible way to encode but couldn't find the solution, and I don't have Linux to test code ☹
> > Here's the screenshot 📸 : **npm test**
> > ![2020-12-18_10_55_57_Code](https://user-images.githubusercontent.com/40760103/102579497-90dc9200-4122-11eb-86a7-fd82619cbeb4.jpg)
> > What's solution of this issue ??
> 
> https://stackoverflow.com/questions/45575863/how-to-print-utf-8-strings-to-stdcout-on-windows
> 
> I haven't tried but, check this

hey!! can you please help me .. because I assume that my code is correct but still test cases are failing .. 
here is the screnshot 
![Screenshot (47)](https://user-images.githubusercontent.com/73290803/102713297-4fe4a900-42ed-11eb-8db8-72df881ce7d3.png)

**Comment by farhaanxxiv** [comment]
> hey!! can you please help me .. because I assume that my code is correct but still test cases are failing ..
> here is the screnshot
> ![Screenshot (47)](https://user-images.githubusercontent.com/73290803/102713297-4fe4a900-42ed-11eb-8db8-72df881ce7d3.png)

Does your cli work when you add/del/done the items? Did you test your app by manually giving arguments?

**Comment by ShyamDev12** [comment]
> > hey!! can you please help me .. because I assume that my code is correct but still test cases are failing ..
> > here is the screnshot
> > ![Screenshot (47)](https://user-images.githubusercontent.com/73290803/102713297-4fe4a900-42ed-11eb-8db8-72df881ce7d3.png)
> 
> Does your cli work when you add/del/done the items? Did you test your app by manually giving arguments?

yes bro I am also facing this issue and I tested manually its working fine but the test cases are failing help .

**Comment by ShyamDev12** [comment]
> > > todo app took 4-5 hours to code in **C++** on **Windows 10** 😊, but "\n" is converted to dot(·)
> > > its been 1 day, but couldn't find the solution......
> > > I tried every possible way to encode but couldn't find the solution, and I don't have Linux to test code ☹
> > > Here's the screenshot 📸 : **npm test**
> > > ![2020-12-18_10_55_57_Code](https://user-images.githubusercontent.com/40760103/102579497-90dc9200-4122-11eb-86a7-fd82619cbeb4.jpg)
> > > What's solution of this issue ??
> > 
> > 
> > https://stackoverflow.com/questions/45575863/how-to-print-utf-8-strings-to-stdcout-on-windows
> > I haven't tried but, check this
> 
> hey!! can you please help me .. because I assume that my code is correct but still test cases are failing ..
> here is the screnshot
> ![Screenshot (47)](https://user-images.githubusercontent.com/73290803/102713297-4fe4a900-42ed-11eb-8db8-72df881ce7d3.png)

ya same issue here pls help

**Comment by abhi5878** [comment]
> se I was having

were you using c++, or other language?

If c++, can you tell how you resolved this issue.

**Comment by ForgottenProgramme** [comment]
> @inst-cicada Could you check for trailing spaces in your output? It's likely that the _dot_ character is being used to indicate additional spaces at the end of the line in your output.
> 
> The test doesn't handle additional spaces _within_ the output lines, at the moment.

How to rectify this?

**Comment by AkkapelliHarshith** [comment]
I was unable to submit my zip file. Though i was uploading a file with .zip extension , it is giving me error as:
**You must upload a ZIP file to submit** 
Can some help?

**Comment by ForgottenProgramme** [comment]
It says 'remove any binary file before uploading'. 
Also, should the done.txt and todo.txt files be empty in my zip folder that I want to upload?

**Comment by ForgottenProgramme** [comment]
Should I also remove the 'package-lock' folder from my zip folder that I want to upload?
@harigopal

**Comment by ForgottenProgramme** [comment]
@MrAdiii

**Comment by gd-arch** [comment]
i found a solution which should work on most of the languages :
 Use \n instead of println methods for ex- in java rather than using System.out.println("text") use System.out.print("text \n") this will work because println methods uses platform dependent line separators whereas \n is platform independent.
In py- print("text",end=''\n") this should work

**Comment by Balaji-Pa** [comment]
> ![image](https://user-images.githubusercontent.com/40322760/102711963-96350a80-42e3-11eb-8472-a7859bbf1924.png)
> 
> Hi why is it throwing error? I am not printing full stops but they are automatically being appended
> IN java
I too facing this same issue. Can anyone suggest a solution for this.

**Comment by YashwantChauhan** [comment]
> > ![image](https://user-images.githubusercontent.com/40322760/102711963-96350a80-42e3-11eb-8472-a7859bbf1924.png)
> > Hi why is it throwing error? I am not printing full stops but they are automatically being appended
> > IN java
> > I too facing this same issue. Can anyone suggest a solution for this.

I think there is no proper answer to this for C++ , either code in pyhton or check in Linux, I struggled with the same problem , I think maybe our cases will pass in their server even when they are not passing for us( because we are using windows which does not uses utf8 encoding ) , just focus on getting the content right and pass the rest of the test parts. Tests can pass in their server because the dot(.) will not be inserted there( I guess );

**Comment by chawlajay** [comment]
> todo app took 4-5 hours to code in **C++** on **Windows 10** 😊, but "\n" is converted to dot(·)
> its been 1 day, but couldn't find the solution......
> I tried every possible way to encode but couldn't find the solution, and I don't have Linux to test code ☹
> Here's the screenshot 📸 : **npm test**
> ![2020-12-18_10_55_57_Code](https://user-images.githubusercontent.com/40760103/102579497-90dc9200-4122-11eb-86a7-fd82619cbeb4.jpg)
> 
> What's solution of this issue ??

Hey, did you find the solution? what to do to solve this in C++ ?

**Comment by chawlajay** [comment]
> **Expected: StringContaining "[3] find needle in the haystack [2] water the plants [1] the thing i need to do " Received: "[3] find needle in the haystack· [2] water the plants· [1] the thing i need to do·**
> "
> 
> I tried to put **\n**, **different print()**, and also tried **tripple quoted strings** but I dont know from where that **(·)dot** comes when I test the code with **npm test**. While testing with my powershell everything is fine with no dots but with npm test there is dots. Please help.
> 
> Name: Abhishek Joshi

any solution of this in C++ ?

**Comment by udaygajavalli** [comment]
> It says 'remove any binary file before uploading'.
> Also, should the done.txt and todo.txt files be empty in my zip folder that I want to upload?

Remove the `node_modules` folder and any binary or hidden files like `.vscode` or `.gitignore`

**Comment by ultralegendary** [comment]
Hi, i am having trouble in getting started.
In the readme.md, under ## Getting started, i dont know how to do point 3. I wrote my code in todo.cpp, now  what it mean "make app".
Can any one please help me out.

**Comment by ankitaYadav02** [comment]
I am unable to uplaod my zip file it says application error at heroku app

**Comment by shreedhar37** [comment]
> The same error persists in my system too. I'm using python and regardless of whatever is done, regex, strip, split, join; nothing works. Removing whitespace, newlines, others, nothing is working.
> What is to be done?

same here

**Comment by agmona** [comment]
![Uploading IMG20201224181811.jpg…]()
I got stuck at this point, please help me to resolve this out.

**Comment by ultralegendary** [comment]
![temp_1](https://user-images.githubusercontent.com/67859954/103098442-c9073780-4630-11eb-9394-d2f24186723c.png)
I don't know why i get this error msg while running npm test
`.\todo.out is not recognized as an internal or external command'
Can any one figure out what i am doing wrong?

**Comment by ultralegendary** [comment]
> I don't know why i get this error msg while running npm test
> `.\todo.out is not recognized as an internal or external command'
> Can any one figure out what i am doing wrong?
> 
>  and am not able to upload the image ☹️ Error while uploading IMG-20201224-WA0010.png

**Comment by rohitpawar2811** [comment]
> ![Screenshot (39)](https://user-images.githubusercontent.com/73290803/102700908-98fa1600-4277-11eb-878b-974ff2be408d.png)
> Here it works fine when I manually type ./todo

can you plzz tel me how would you can run using ./todo because its not working in my system

**Comment by ShashiVardhan09** [comment]
> > > > todo app took 4-5 hours to code in **C++** on **Windows 10** blush, but "\n" is converted to dot(·)
> > > > its been 1 day, but couldn't find the solution......
> > > > I tried every possible way to encode but couldn't find the solution, and I don't have Linux to test code frowning_face
> > > > Here's the screenshot camera_flash : **npm test**
> > > > ![2020-12-18_10_55_57_Code](https://user-images.githubusercontent.com/40760103/102579497-90dc9200-4122-11eb-86a7-fd82619cbeb4.jpg)
> > > > What's solution of this issue ??
> > > 
> > > 
> > > https://stackoverflow.com/questions/45575863/how-to-print-utf-8-strings-to-stdcout-on-windows
> > > I haven't tried but, check this
> > 
> > 
> > hey!! can you please help me .. because I assume that my code is correct but still test cases are failing ..
> > here is the screnshot
> > ![Screenshot (47)](https://user-images.githubusercontent.com/73290803/102713297-4fe4a900-42ed-11eb-8db8-72df881ce7d3.png)
> 
> ya same issue here pls help

you need to create a txt file to insert list data

**Comment by Khiladi2020** [comment]
> **Expected: StringContaining "[3] find needle in the haystack [2] water the plants [1] the thing i need to do " Received: "[3] find needle in the haystack· [2] water the plants· [1] the thing i need to do·**
> "
> 
> I tried to put **\n**, **different print()**, and also tried **tripple quoted strings** but I dont know from where that **(·)dot** comes when I test the code with **npm test**. While testing with my powershell everything is fine with no dots but with npm test there is dots. Please help.
> 
> Name: Abhishek Joshi

everything is working fine on Linux platform this problem is only on windows.
So dont worry if your solution is only failing on those 3 tests

**Comment by rohitpawar2811** [comment]
> > todo app took 4-5 hours to code in **C++** on **Windows 10** 😊, but "\n" is converted to dot(·)
> > its been 1 day, but couldn't find the solution......
> > I tried every possible way to encode but couldn't find the solution, and I don't have Linux to test code ☹
> > Here's the screenshot 📸 : **npm test**
> > ![2020-12-18_10_55_57_Code](https://user-images.githubusercontent.com/40760103/102579497-90dc9200-4122-11eb-86a7-fd82619cbeb4.jpg)
> > What's solution of this issue ??
> 
> Hey, did you find the solution? what to do to solve this in C++ ?

hey my first test case which is invisible not solving you have some idea to solve this issue

**Comment by rohitpawar2811** [comment]
> ![Screenshot (38)](https://user-images.githubusercontent.com/73290803/102700841-f5106a80-4276-11eb-8474-6cd235c08272.png)
> 
> Help me please!!
> having problem to run todo
> it runs fine when I manually type ./todo
> but when it was manually opend by test this error occurs " C:\Users\Neelam\OneDrive\Desktop\project\java/todo"
> How to fix this??

change the todotest.js in which (.) may be not present and add it to there.(./todo)

**Comment by Gourav2K** [comment]
I'm unable to understand where exactly am I supposed to have the text files. Because it always throws an error that text file is missing in the directory. When I put the text file manually, after running a test, the files disappear on their own. Would appreciate if someone could help

**Comment by Gourav2K** [comment]
Should the text files be present elsewhere and not in the application directory?

**Comment by samarthshiramshetty** [comment]
Hey, If someone has completed the app. can you share the source code?

**Comment by jasim** [comment]
@samarthshiramshetty Please see the README of the repo:

Kindly desist from sharing your solution privately or publicly. This is because the programming task is not complex for those who've written non-trivial amount of code before. But for beginners, solving this can be quite instructive - frustrating at times, but rewarding in the end.

But if you share your solution with them - through a GitHub repo, or by circulating in your private networks, you're only robbing them of a rewarding experience that would have helped them grow as programmers.

It is trivial to detect copy-cat code submissions and students who submit plagiarized code will be unable to find a place among the limited seats in the course. It is just that it'll take us a few more moments to read through the code and tag it. A lose-lose proposition for all concerned.
