### ISSUE TITLE
Mismatch in README.md and tests

### ISSUE THREAD

**Issue by Karnak123** [nseadlc-2020/package-todo-cli-task#14]
The readme tells to print report as 
```
dd/mm/yyyy Pending : 1 Completed : 4
```
However the test checks using format
```
yyyy-mm-dd Pending : 1 Completed : 4
```

**Comment by bodhish** [comment]
Thanks for pointing it out. 
Fixed in https://github.com/nseadlc-2020/package-todo-cli-task/commit/f43a64e62af24d03da82570ba343d0d0f1fb71ad
