### ISSUE TITLE
Tests fail when __dirname contains spaces

### ISSUE THREAD

**Issue by sauravUppoor** [nseadlc-2020/package-todo-cli-task#15]
In my Windows machine, when I run _npm test_ I get an error due to spaces in my file path. So I replaced the line 
`` let todoTxtCli = (...args) => [`${__dirname}/todo`, ...args].join(" ");`` with  ``let todoTxtCli = (...args) => [\`"${__dirname}"\\todo`, ...args].join(" ");`` and the tests ran perfectly. Do I keep these changes while submitting my work?

**Comment by jcsherin** [comment]
@sauravUppoor You don't have to submit the changes you made to the test script. 

Also please email us for any further queries, rather than raising an issue here.
