### ISSUE TITLE
Documentation error in markdown file: in command 'report', asked datetime format in md is dd/mm/yyyy, but while checking 'todo.test.js' contains checking in 'date.toISOString()', i.e. in yyyy-mm-dd format

### ISSUE THREAD

**Issue by Aanzil** [nseadlc-2020/package-todo-cli-task#16]
I am attaching the snapshots regarding the same. Please update either ! Otherwise, no one is going to successfully pass npm test. Although I have passed it.

$ ./todo.test.js
![Screenshot from 2020-12-17 20-30-48](https://user-images.githubusercontent.com/57168110/102504539-fa1ebf80-40a6-11eb-891a-db6c8456e0fb.png)
$ ./README.md
![Screenshot from 2020-12-17 20-31-13](https://user-images.githubusercontent.com/57168110/102504591-07d44500-40a7-11eb-9f44-776c9dd30399.png)

**Comment by jcsherin** [comment]
@Aanzil Thanks for the report. We have fixed the documentation to match the test date format.
