### ISSUE TITLE
Date issue, UTC or local

### ISSUE THREAD

**Issue by Mysterious-Owl** [nseadlc-2020/package-todo-cli-task#17]
The test expects time in UTC, so in report and done.txt, does the time need to be local or in UTC?
Todo list will be more effective with local time.
I can update the todo.test.js, if needed, to use local time instead of UTC

**Comment by jcsherin** [comment]
We are aware of this issue. It is a defect in the test. It should have been local time and not UTC. For the code submission you can use either local or UTC timezone.
