### ISSUE TITLE
Tailor made getting started instructions

### ISSUE THREAD

**Issue by jcsherin** [nseadlc-2020/package-todo-cli-task#2]
The [getting started](https://github.com/jcsherin/package-todo-cli-task/tree/master/shared#getting-started) should be specific to the language which is being packaged. This is now written specifically for Node.

One way of going about is by creating a getting started markdown in each of the language directories. The build step can then merge it with the shared `README.md`.

The getting started instructions should cover,
1. Compiler, development and other runtime dependencies
2. Installing `Node.js` and dependencies for testing
3. How to build and execute the code 
4. How to run the tests

**Comment by bodhish** [comment]
Done.
