### ISSUE TITLE
Cannot find ./todo

### ISSUE THREAD

**Issue by parakh7055** [nseadlc-2020/package-todo-cli-task#20]
![Screenshot from 2020-12-18 20-10-46](https://user-images.githubusercontent.com/76216583/102626721-30267700-416d-11eb-94cb-61bf011f8542.png)
 i install all the dependencies by  running npm install i worked on ubuntu and please write the task in more clear way

**Comment by amit-kr-debug** [comment]
first 
$ ./todo.sh
then
{you may need to change mode before this}
$ ln -s todo.sh todo

then run the command 
$ npm test
