### ISSUE TITLE
test case has not passed even after correcting the presentation. Please look into it.

### ISSUE THREAD

**Issue by amit-kr-debug** [nseadlc-2020/package-todo-cli-task#21]
![image](https://user-images.githubusercontent.com/68914475/102639054-7afcba80-417e-11eb-811f-99e3463bbd8f.png)

**Comment by MrAdiii** [comment]
Open your todo.txt and done.txt check if there is any **\0** in it.

\0 is the escape sequence for the null character

**Comment by Mani5871** [comment]
Can anyone help me regarding how to take the input according to the provided test cases. I completed the problem by taking the input in the cmd terminal. I installed nodejs and npm. I also runned the command 'npm test'. I got that testcases are failed. But I am unable to continue after that to integrate to code. Can anyone help me in this regard?

**Comment by law27** [comment]
@Mani5871 Provide more info about your issue to reproduce

**Comment by amit-kr-debug** [comment]
> Open your todo.txt and done.txt check if there is any **\0** in it.
> 
> \0 is the escape sequence for the null character

Thanks for your response but 
the problem solved when I used todo.test.js of python_3 which I download from here. 
https://github.com/nseadlc-2020/package-todo-cli-task/blob/master/_build/fellowship-python.zip

**Comment by Mani5871** [comment]
> @Mani5871 Provide more info about your issue to reproduce

![output](https://user-images.githubusercontent.com/58336312/102680581-8e8c3d80-41df-11eb-993c-bd4be85def31.jpg)
![power](https://user-images.githubusercontent.com/58336312/102680142-c85b4500-41db-11eb-9a80-27b37cc40f2c.jpg)

In the power shell, I executed the command npm test. But none of the test cases are passed. But when I run the code in an online compiler, I got the required output. Can you please assist me in this regard?

**Comment by law27** [comment]
@Mani5871 You're asked to take input via command line arguments not from standard I/O.
In C/C++ you can extract via `main(int argc, char** argv)`. **argc** is the argument count and **argv** is the arguments you've passed via the command line.
You can learn about this [here](https://www.geeksforgeeks.org/command-line-arguments-in-c-cpp/)

**Comment by Mani5871** [comment]
> @Mani5871 You're asked to take input via command line arguments not from standard I/O.
> In C/C++ you can extract via `main(int argc, char** argv)`. **argc** is the argument count and **argv** is the arguments you've passed via the command line.
> You can learn about this [here](https://www.geeksforgeeks.org/command-line-arguments-in-c-cpp/)

I implemented using command line arguments. For multi line arguments, I also used single quotes. But still I am unable to pass the tests.
![cmd](https://user-images.githubusercontent.com/58336312/102687739-1b062280-4217-11eb-8ddc-71bfa6ff66fb.jpg)

**Comment by law27** [comment]
@Mani5871 If you've experience with JS check out the todo.test.js it describes all the test for the program.
You need some file handling concepts in C to complete this program and you can't run this program in a online compiler.
- See whether you can utilize the make file
- Check out the todo.bat file and see what kind of binary file it is expecting inorder to run the program because jest test suite relies on todo.bat file for executing and testing the program.
- If you can install a C compiler in your local machine instead of using Online compilers
- Read README.md file bundled with the starter pack
