### ISSUE TITLE
del keyword in python

### ISSUE THREAD

**Issue by akshatshukla175** [nseadlc-2020/package-todo-cli-task#23]
facing difficulty in implementing del function in python as 'del' is a reserved keyword in Python 3.

**Comment by satyabansahoo2000** [comment]
Did u found any solution to this?? I am facing the same error. Can we change the name.

**Comment by mohanraams** [comment]
i have asolution for it did u resolve it ,or shall i unveil here!!

**Comment by mohanraams** [comment]
what solution did u posses even i could learn from ur side??

**Comment by satyabansahoo2000** [comment]
No i didn't find any. Please provide it.

**Comment by mohanraams** [comment]
TRY USING SOME MODULE 
TO MATCH THE FUNCTION NAME WITH THE CLI INPUT FUNCTION NAME
USE DICTIONARY TO MATCH THE NAMES OF THE FUNCTION WITH THE INPUT

I THINK YOU GOT SOME IDEA
HAPPY LEARNING

**Comment by satyabansahoo2000** [comment]
Okay I will give it a try. Thanks for the help.

**Comment by sarathsajan** [comment]
> 
> 
> facing difficulty in implementing del function in python as 'del' is a reserved keyword in Python 3.

I had the same issue and I asked in SO, hope it helps. The problem has been solved in this [StackOverflow Question](https://stackoverflow.com/questions/65517801/python-del-syntax-error-when-used-as-a-variable-name
)

**Comment by satyabansahoo2000** [comment]
@sarathsajan thanks it helped a lot. Though, I am using a different package **click** to create CLI, still helpful.

I got this for click, ```@main.command(name='del')```
