### ISSUE TITLE
Unable to pass the test cases

### ISSUE THREAD

**Issue by Mani5871** [nseadlc-2020/package-todo-cli-task#25]
I am trying to run my code using the npm test command. But  none of the test cases are passed. But, when I tried out manually, I got the expected output. Can anyone please help me out? The below are the commands I used manually to run my code.

./todo help
./todo add "water the plants"
./todo add "change bulb"
./todo add "bring groceries"
./todo add "read a book"
./todo add "clean the house"
./todo add "bring medicines"
./todo ls
./todo del 34
./todo del 3
./todo ls
./todo report
./todo done 9
./todo done 2
./todo ls
./todo report
exit

The below is the output for above test cases.
![case](https://user-images.githubusercontent.com/58336312/102681059-4cb1c600-41e4-11eb-87af-2502f1f6e46d.jpg)

But when I am running the command npm test, none of the test case passed. Can anyone please help me in this manner? The below is the output when I tried to run the command on power shell

![power](https://user-images.githubusercontent.com/58336312/102681074-7ff45500-41e4-11eb-99a2-b450ce9d7096.jpg)

Thanks in advance

**Comment by amanasci** [comment]
This is error is due to white space in your folder name `Program Files`. 
Because of white space when executing test the directory path splits into two seperate arguments instead of complete path.

> You can either rename your directory or move project to some other directory with no wihte spaces in name. Make sure you don't have white spaces in your directory names. (That's the simplest solution)

**Comment by saikumarjetti** [comment]
> I am trying to run my code using the npm test command. But none of the test cases are passed. But, when I tried out manually, I got the expected output. Can anyone please help me out? The below are the commands I used manually to run my code.
> 
> ./todo help
> ./todo add "water the plants"
> ./todo add "change bulb"
> ./todo add "bring groceries"
> ./todo add "read a book"
> ./todo add "clean the house"
> ./todo add "bring medicines"
> ./todo ls
> ./todo del 34
> ./todo del 3
> ./todo ls
> ./todo report
> ./todo done 9
> ./todo done 2
> ./todo ls
> ./todo report
> exit
> 
> The below is the output for above test cases.
> ![case](https://user-images.githubusercontent.com/58336312/102681059-4cb1c600-41e4-11eb-87af-2502f1f6e46d.jpg)
> 
> But when I am running the command npm test, none of the test case passed. Can anyone please help me in this manner? The below is the output when I tried to run the command on power shell
> 
> ![power](https://user-images.githubusercontent.com/58336312/102681074-7ff45500-41e4-11eb-99a2-b450ce9d7096.jpg)
> 
> Thanks in advance



> I am trying to run my code using the npm test command. But none of the test cases are passed. But, when I tried out manually, I got the expected output. Can anyone please help me out? The below are the commands I used manually to run my code.
> 
> ./todo help
> ./todo add "water the plants"
> ./todo add "change bulb"
> ./todo add "bring groceries"
> ./todo add "read a book"
> ./todo add "clean the house"
> ./todo add "bring medicines"
> ./todo ls
> ./todo del 34
> ./todo del 3
> ./todo ls
> ./todo report
> ./todo done 9
> ./todo done 2
> ./todo ls
> ./todo report
> exit
> 
> The below is the output for above test cases.
> ![case](https://user-images.githubusercontent.com/58336312/102681059-4cb1c600-41e4-11eb-87af-2502f1f6e46d.jpg)
> 
> But when I am running the command npm test, none of the test case passed. Can anyone please help me in this manner? The below is the output when I tried to run the command on power shell
> 
> ![power](https://user-images.githubusercontent.com/58336312/102681074-7ff45500-41e4-11eb-99a2-b450ce9d7096.jpg)
> 
> Thanks in advance

The director programs fills is causing the issue.
To solve it change the director name as programs_files or test the code in a director where the director name has no space in between.

**Comment by Mani5871** [comment]
> This is error is due to white space in your folder name `Program Files`. 
> Because of white space when executing test the directory path splits into two seperate arguments instead of complete path.
> 
> > You can either rename your directory or move project to some other directory with no wihte spaces in name. Make sure you don't have white spaces in your directory names. (That's the simplest solution)
> 

Yeah, I tried that one. Again I am facing the same issue
