### ISSUE TITLE
Testing will add · in end of every string

### ISSUE THREAD

**Issue by AravindPugal** [nseadlc-2020/package-todo-cli-task#29]
when I run my python file myself everything works fine but during testing of the file(with todo.test.js) all the new line characters are convrted to · (may be ascii value of new line character) . It would be due to utf encoding but I don't know how to get rid of this.My operating sytem is windows.Will you please anyone tell me what is the reason for this issue wheather it's mine or utf encoding.

**Comment by jcsherin** [comment]
[Refer to this issue](https://github.com/nseadlc-2020/package-todo-cli-task/issues/12)
