### ISSUE TITLE
Executation of  todo app on Window machine

### ISSUE THREAD

**Issue by mohit355** [nseadlc-2020/package-todo-cli-task#30]
I want to add few points in **getting_started.md**  related to executing the todo app in the Windows machine.

 We can run the  Batch file by the following 
               
**Power Shell**
```
      ./todo 
```
or
```
    ./todo.bat
```

**Command Prompt**
   ```
       .\todo
```
or
```
    .\todo.bat
```

![Screenshot (268)](https://user-images.githubusercontent.com/54148372/102696020-5887a180-4251-11eb-8028-1066f04f47bd.png)

![Screenshot (269)](https://user-images.githubusercontent.com/54148372/102696028-6c330800-4251-11eb-8c96-e332af6648d8.png)

In the attached Images it is clear that we can use both commands to run the batch file. So I want to Update the **Getting_started.md**.

**Comment by jcsherin** [comment]
@mohit355 Thanks for pointing this out. We already have a [section added to the README.md regarding paths](https://github.com/nseadlc-2020/package-todo-cli-task/blob/master/shared/Test.md#a-note-about--for-windows-users) for Windows users.
