### ISSUE TITLE
Unable to run test cases on todo.py 

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [nseadlc-2020/package-todo-cli-task#32]
I written code for todo application in todo.py . I have python installed in my system variable and node.js installed too. But whenever . I have installed all needed dependencies using npm install . But when I run  test cases using 'npm test' it gives error - "Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases." Even python is installed globally . I have searched a lot about this error but none of result was satisfactory . 

Anyone knows how to solve this error ?

**Comment by sauravUppoor** [comment]
Maybe its due to the command in todo.bat file. Try replacing `python3` with `python` in todo.bat.

**Comment by Rishabhraghwendra18** [comment]
Thanks ... Now it's working
