### ISSUE TITLE
EOF error

### ISSUE THREAD

**Issue by ShashiVardhan09** [nseadlc-2020/package-todo-cli-task#33]
no matter what changes i do.my input always shows EOF error in python.When i run it on my console it works fine.Error occurs only while running test cases

 Command failed: D:\aicte\python/todo
 Traceback (most recent call last):
   File "todo.py", line 14, in <module>
     s=list(map(str,input().split()))
 EOFError: EOF when reading a line

**Comment by Rishabhraghwendra18** [comment]
you have to make CLI (command line input) in python .
