### ISSUE TITLE
Unspecified required error messages

### ISSUE THREAD

**Issue by MPL0Y** [nseadlc-2020/package-todo-cli-task#35]
In all the `README.md` files in the zips in [_build](https://github.com/nseadlc-2020/package-todo-cli-task/tree/master/_build) folder, clear instructions are not given as to what the program should print if it encounters fewer arguments than expected. Not sure if this is intended for the students to figure out.

### Example
While encountering fewer arguments in the `add` option, a specific message of "Error: Missing todo string. Nothing added!" is expected. Otherwise, the `npm test` command fails some tests.

Close if it was intended.

**Comment by Rishabhraghwendra18** [comment]
Ya..same I am thinking

**Comment by jcsherin** [comment]
@MPL0Y The `README` does not exhaustively specify the behaviour of the program. We expect those who download the starter kits to be able to run the tests locally. The tests themselves being code are better for specifying whether the implementation is complete & correct. Also we hope this exposes those who work on the problem to test driven development.
