### ISSUE TITLE
Specifying the version of the programming language used in README file

### ISSUE THREAD

**Issue by ForgottenProgramme** [nseadlc-2020/package-todo-cli-task#40]
There should be a provision to add the version of the programming language that the student has used to write the source code. 
This will make sure that any incompatibilities are easy to spot and diagnose.

**Comment by jasim** [comment]
@ForgottenProgramme Can you elaborate with an example? Thanks.

**Comment by ForgottenProgramme** [comment]
@jasim , sure!

Look at this screenshot of the README file provided in the starter zip file. 

![image](https://user-images.githubusercontent.com/65779580/102774361-d8784d80-43b0-11eb-8a48-e088c5dbba5c.png)


So, the README is written to as to help the student set up the environment and understand what all functionalities  the CLI - todo application should have. 

There  should be a block/space in this README file, where each student can mention the version of the programming language they wrote their code in. 

There are some routines/functions that might be introduced in a new version of the programming language. And the tester might be using an older version which doesn't support these functions. (For example C++ 14 doesn't support a number of functionalities that C++ 17 does)
And on the flip case, the student might have written the code in an older version of the programming language and some functions they used might be obsolete in the newer version that the tester might be using.

So, the README file should have a space where the student is supposed to write the version they are using on their system.

**Comment by jasim** [comment]
Thanks @ForgottenProgramme, that makes sense.

We do the testing using the latest versions of all supported languages, but as you said we might miss advanced language features in certain scenarios (language extensions, pragmas, transpiling etc.)

This is accounted for in the process and it does not affect your chance of getting into the program. However for the next iteration we'll create a more automated way of avoiding this confusion.

**Comment by ForgottenProgramme** [comment]
@jasim, Thankyou. 
One question: Was I supposed to add the symbolic link file in the zip folder that I uploaded?
