### ISSUE TITLE
Test cases Failure due to keyword error

### ISSUE THREAD

**Issue by satyabansahoo2000** [nseadlc-2020/package-todo-cli-task#43]
As ```del``` is a keyword in Python, I can't use it as a function name. Any solution for this??

**Comment by satyabansahoo2000** [comment]
@jcsherin thats a genuine issue, can u please elaborate on this before closing it?

**Comment by sarathsajan** [comment]
I had the same issue and I asked in SO, hope it helps. The problem has been solved in this [StackOverflow Question](https://stackoverflow.com/questions/65517801/python-del-syntax-error-when-used-as-a-variable-name
)

**Comment by sarathsajan** [comment]
> 
> 
> @jcsherin thats a genuine issue, can u please elaborate on this before closing it?

I had the same issue and I asked in SO, hope it helps. The problem has been solved in this [StackOverflow Question](https://stackoverflow.com/questions/65517801/python-del-syntax-error-when-used-as-a-variable-name
)
