### ISSUE TITLE
Error in provided output 

### ISSUE THREAD

**Issue by manasvinsharma** [nseadlc-2020/package-todo-cli-task#49]
![error](https://user-images.githubusercontent.com/55654162/103340330-c762c700-4aa9-11eb-80ce-51efc4a3f7a4.jpeg)

1) I am facing this error in which the double quote at the end of last todo is occurring in same line while according to the output it should occur in next line.  

2) I have tried a lot but its not working . It looks like that there is some error in  todo.test.js file.

3) I have tried to give "/n" or "  " but it looks like that some trimming is done  of whitespaces, blanks in js file.

**Comment by J-Raghav** [comment]
These is not an issue
you should add "\n" at the end of your "ls"  command output and test case will pass
