### ISSUE TITLE
Error while run npm run test 

### ISSUE THREAD

**Issue by Z4nzu** [nseadlc-2020/package-todo-cli-task#53]
![Screenshot from 2021-01-03 14-09-45](https://user-images.githubusercontent.com/25708027/103474861-e45f0900-4dcd-11eb-9699-9d5820303073.png)
![Screenshot from 2021-01-03 14-10-25](https://user-images.githubusercontent.com/25708027/103474862-e628cc80-4dcd-11eb-81b3-b2d9cf780297.png)

Anyone can please help to solve this error.

**Comment by itspyguru** [comment]
same issue, did you found the solution ?
