### ISSUE TITLE
If anyone is having problems related to running tests on windows (Javascript)

### ISSUE THREAD

**Issue by shivankacker** [nseadlc-2020/package-todo-cli-task#59]
Keep getting a popup for windows unable to find a program to run .sh files? Easy fix you can apply : 

Go to task.test.js
locate the line :
let tasksTxtCli = (...args) => ['${__dirname}/task.sh', ...args].join(" ");

and change it to :
`let tasksTxtCli = (...args) => ['node '+__dirname+'/task.js', ...args].join(" ");`

and it works!

**Comment by itspyguru** [comment]
didn't work

**Comment by shivankacker** [comment]
> 

So github kind of messed up with the quotation marks. I have edited the code, so try that one.

**Comment by itspyguru** [comment]
do you know, why in my tests, the received value is empty. I'm using python and using print function to display output

![Screenshot (305)](https://user-images.githubusercontent.com/71623767/145701666-084d1b07-2fee-433a-b04b-949d92c56283.png)

**Comment by shivankacker** [comment]
This thread is for Javascript. I do not hold strong knowledge in python so I will advice you to get in touch with the GDC team. 
Of what I can see from the screenshot, the problem is likely to be similar as to the one I wrote about, just in Python.

**Comment by itspyguru** [comment]
I re-downloaded the task zip file and it works now. I think they have updated it now
