### ISSUE TITLE
while doing tests, received shows "" for the code outputs written using print() in python

### ISSUE THREAD

**Issue by itspyguru** [nseadlc-2020/package-todo-cli-task#63]
![Screenshot (305)](https://user-images.githubusercontent.com/71623767/145689151-3f33db88-aef4-4395-8803-e663948adba6.png)

In all the test cases, received remains ""

**Comment by Nirbhay007** [comment]
Hey, I am having the same problem, did you find any solution to this?

**Comment by mehul-2000** [comment]
Have you got the solution for this same problem ?

**Comment by shivani939** [comment]
I am also facing the same problem

**Comment by bodhish** [comment]
This is an old repo that deals with an old task. 

Please refer the [FAQ Doc](https://docs.google.com/document/d/1bucwQX-W9I0caluO758iENX9pKhIVGSdOViQsidp8KQ/edit?usp=drivesdk) for the new task

**Comment by itspyguru** [comment]
Re-download the python task folder from the website, they have fixed it and it's now working
