### ISSUE TITLE
Issue with the task.bat file for python

### ISSUE THREAD

**Issue by VishalHaswani** [nseadlc-2020/package-todo-cli-task#64]
The currently existing task.bat file contains
```
@echo off

python3 task.py %1 %2 %3

```
now when i try to run `> .\task add 2 hello world`, it only passes the first 3 arguments to the python file which are "add 2 hello" and the 4th argument is lost.

I suggest kindly update the file to this
```
@echo off

python3 task.py %*

```

Here `%*` is used to pass all arguments.

**Comment by localhost-8000** [comment]
@VishalHaswani in javascript it is instructed to pass arguments like 
`task add 4 "hello world"`
And this will work fine if in .bat file  _%1 %2 %3_  is present as above arguments will be parsed as:-
arg[0] = add
arg[1] = 4
arg[2] = "hello world"

**Comment by VishalHaswani** [comment]
@Ankur-9598 you are right but in the zip file given in the website the help section does not shown `""` to make sure that the inverted comas don't create a bug i suggested this.

**Comment by localhost-8000** [comment]
@VishalHaswani in javascript zip file it is given...don't have an idea about python. Try to use it once...see if this resolves your problem or not

**Comment by VishalHaswani** [comment]
Thank you for the response my issue is resolved @Ankur-9598 .
