### ISSUE TITLE
Need Help in resolving this error!

### ISSUE THREAD

**Issue by ashwin308200** [nseadlc-2020/package-todo-cli-task#65]
![image](https://user-images.githubusercontent.com/86219952/146780362-b34b933f-3e0b-42d6-9695-91842a5065c6.png)

**Please someone Help me with this, I am stuck in this.**

It shows error even when the expected and received are same.

**Comment by ashwin308200** [comment]
I found a lead in this error, there is an extra \n in the testcase file (\n\n). When I removed the extra \n and change it to (\n) it is correctly working now. @jcsherin Please update it in the test case file.

**Comment by bodhish** [comment]
@ashwin308200 please don't spam this repo. Your task is different.
